### PR TITLE
fix: decrease debounce rate to allow scanner to enter input [CU-rz91a4]

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-rz91a4 Question:  Warehouse location that can be bar-coded](https://app.clickup.com/t/rz91a4)

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/frappe/pull/12875).

**Comment by Alchez** [comment]
@vjFaLk, this might result in more network calls. Do you want to somehow track this, or we'll just leave it to Sentry?

**Comment by Alchez** [comment]
Closing for now, will reopen if this becomes an issue again.

**Pull request closed without merging**
