### PR TITLE
feat: allow number cards in workspaces [CU-2z5cy32]

### PR DESCRIPTION
**Pull request by Alchez**
image

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-2z5cy32 Migrate Parsimony to v14](https://app.clickup.com/t/2z5cy32)

**Comment by ghost** [comment]
### Features

* allow number cards in workspaces ([0380aad](https://github.com/ParsimonyGit/frappe/commit/0380aad2c5e7c68a6d6717c1d4b1ed811e8b1778))


### Contributors

<a href="https://github.com/Alchez">Alchez</a>

<details>
<summary>Commit-Lint commands</summary>
<br />

You can trigger Commit-Lint actions by commenting on this PR:
- `@Commit-Lint merge patch` will merge dependabot PR on "patch" versions (X.X.Y - Y change)
- `@Commit-Lint merge minor` will merge dependabot PR on "minor" versions (X.Y.Y - Y change)
- `@Commit-Lint merge major` will merge dependabot PR on "major" versions (Y.Y.Y - Y change)
- `@Commit-Lint merge disable` will desactivate merge dependabot PR
- `@Commit-Lint review` will approve dependabot PR
- `@Commit-Lint stop review` will stop approve dependabot PR



</details>

**Comment by Alchez** [comment]
Made upstream to [develop](https://github.com/frappe/frappe/pull/20065)

**Comment by Alchez** [comment]
This change was backported to upstream v14 with some additional changes, so closing.

**Pull request closed without merging**
