### PR TITLE
fix: prevent deadlocks with Activity Log via hooks [CU-qh6xaj]

### PR DESCRIPTION
**Pull request by Alchez**

### CODE REVIEW

**Comment by vjFaLk** [comment]
Task linked: [CU-qh6xaj Sales are falling at Demo](https://app.clickup.com/t/qh6xaj)

**Comment by vjFaLk** [comment]
@Alchez interesting...are you sure this is it? When is that function triggered?

**Comment by Alchez** [comment]
This is actually a query fix, like the ones I was mentioning on call yesterday. There could be multiple ones like this one that are causing deadlocks.

This is triggered via daily (not long) hooks as well.

**Comment by Alchez** [comment]
I don't think we're seeing this anywhere right now. Closing for now, can reopen later.

**Pull request closed without merging**
